<div class="page-tools"><a class="button secondary" href="/program">← Nazaj na program</a><span class="spacer"></span><button class="button primary" data-category-dialog data-create-dialog data-permission="program">＋ Dodaj kategorijo</button></div><div class="role-grid">
% for category in categories:
<article class="card role-card"><span class="role-icon">♫</span><div><h3>{{category['name']}}</h3><p>{{category['description'] or 'Brez opisa.'}}</p><span class="muted">{{category['count']}} pesmi</span></div><div class="role-actions" data-permission="program"><button class="icon-button" data-category-edit="{{category['id']}}" aria-label="Uredi kategorijo {{category['name']}}">✎</button>
% if category['count'] == 0:
<form method="post" action="/kategorije/{{category['id']}}/izbrisi"><button class="icon-button danger-icon" aria-label="Izbriši kategorijo {{category['name']}}" onclick="return confirm('Res želiš izbrisati kategorijo?')">×</button></form>
% end
</div></article><dialog id="category-edit-{{category['id']}}"><button class="dialog-close category-edit-close" aria-label="Zapri">×</button><form method="post" action="/kategorije/{{category['id']}}/uredi"><p class="eyebrow">Program</p><h2>Uredi kategorijo</h2><label>Ime<input name="name" value="{{category['name']}}" required></label><label>Opis<textarea name="description" rows="3">{{category['description']}}</textarea></label><div class="dialog-actions"><button type="button" class="button secondary category-edit-cancel">Prekliči</button><button type="submit" class="button primary">Shrani spremembe</button></div></form></dialog>
% end
% if not categories:
<div class="empty-state card"><span>♫</span><h3>Ni še nobene kategorije</h3><p>Dodaj prvo kategorijo za razvrščanje programa.</p><button class="button primary" data-category-dialog data-permission="program">Dodaj kategorijo</button></div>
% end
</div><dialog id="category-dialog"><button class="category-dialog-close dialog-close" aria-label="Zapri">×</button><form method="post" action="/kategorije"><p class="eyebrow">Program</p><h2>Dodaj kategorijo</h2><label>Ime<input name="name" required></label><label>Opis<textarea name="description" rows="3"></textarea></label><div class="dialog-actions"><button type="button" class="button secondary category-dialog-cancel">Prekliči</button><button type="submit" class="button primary">Shrani kategorijo</button></div></form></dialog>
