<!doctype html>
<html lang="sl" data-theme="light" data-permissions="{{','.join(sorted(permissions))}}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#163a45"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><title>{{title}} · Upravljanje zbora</title><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/static/icons/icon.svg" type="image/svg+xml"><link rel="apple-touch-icon" sizes="180x180" href="/static/icons/apple-touch-icon.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/static/styles.css?v=8"><link rel="stylesheet" href="/static/refinements.css?v=2"><link rel="stylesheet" href="/static/hotfix.css?v=3"></head>
<body>
<aside class="sidebar"><a class="brand" href="/"><span class="brand-mark">𝄞</span><span>Upravljanje zbora<small>Administracija in program</small></span></a><nav aria-label="Glavna navigacija"><a class="{{'active' if active == 'dashboard' else ''}}" href="/"><span>⌂</span>Nadzorna plošča</a><a class="{{'active' if active in ('members','member_detail','roles') else ''}}" href="/clani"><span>♟</span>Člani zbora</a><a class="{{'active' if active in ('songs','song_detail') else ''}}" href="/program"><span>♫</span>Program zbora</a><a class="{{'active' if active in ('events','event_detail') else ''}}" href="/dogodki"><span>▷</span>Vaje in dogodki</a><a class="{{'active' if active == 'attendance' else ''}}" href="/prisotnost"><span>✓</span>Prisotnost</a><a class="{{'active' if active == 'treasury' else ''}}" href="/blagajna"><span>€</span>Blagajna zbora</a><a class="{{'active' if active == 'gallery' else ''}}" href="/galerija"><span>▧</span>Galerija</a><a class="{{'active' if active == 'chat' else ''}}" href="/klepet"><span>◌</span>Klepet</a></nav><div class="sidebar-footer"><div class="avatar">{{current_user['first_name'][0]}}{{current_user['last_name'][0]}}</div><div><strong>{{current_user['first_name']}} {{current_user['last_name']}}</strong><small>{{', '.join(current_user['roles'])}}</small></div><button class="icon-button" data-account-modal aria-label="Odpri uporabniški meni">•••</button></div></aside>
<main class="main"><header class="topbar"><button class="mobile-menu" aria-label="Odpri meni">☰</button><div><p class="eyebrow">Upravljanje zbora</p><h1>{{title}}</h1></div><div class="top-actions"><a class="home-shortcut" href="/">⌂ Domov</a><button class="icon-button theme-toggle" data-theme-toggle aria-label="Preklopi temni način">◐</button><button class="avatar avatar-button" data-account-modal aria-label="Uporabniški račun {{current_user['first_name']}} {{current_user['last_name']}}">{{current_user['first_name'][0]}}{{current_user['last_name'][0]}}</button></div></header><section class="content">
% include(view, **locals())
</section><footer class="legal-links" aria-label="Informacije o aplikaciji"><a href="/o-aplikaciji">O aplikaciji</a><a href="/zasebnost">Zasebnost</a><a href="/pogoji-uporabe">Pogoji uporabe</a></footer></main>
<div id="toast" role="status" aria-live="polite" data-message="{{message}}"></div>
<dialog id="account-dialog" class="account-dialog"><button class="account-close dialog-close" aria-label="Zapri uporabniški račun">×</button><div class="account-profile"><span class="avatar xlarge">{{current_user['first_name'][0]}}{{current_user['last_name'][0]}}</span><div><p class="eyebrow">Prijavljeni uporabnik</p><h2>{{current_user['first_name']}} {{current_user['last_name']}}</h2><p>{{current_user['email']}}</p></div></div><p class="permission-note"><strong>Vloge:</strong> {{', '.join(current_user['roles'])}}</p><div class="push-settings"><strong>Potisna obvestila</strong><p data-push-status role="status">Preverjam možnost obvestil …</p><button type="button" class="button secondary" data-push-toggle disabled>Vklopi obvestila</button> <button type="button" class="button secondary" data-push-test hidden>Pošlji preizkus</button></div><details class="install-help" data-install-help><summary>Namesti aplikacijo na telefon</summary><p>Android (Chrome): odpri meni ⋮ in izberi »Namesti aplikacijo« ali »Dodaj na začetni zaslon«.</p><p>iPhone (Safari): tapni Deli in nato »Dodaj na domači zaslon«.</p><button type="button" class="button secondary" data-install-trigger hidden>Namesti zdaj</button></details><div class="dialog-actions"><button class="button secondary" data-change-password>Spremeni geslo</button><a class="button danger" href="/odjava">Odjava</a></div></dialog>
<dialog id="change-password-dialog"><button class="change-password-close dialog-close" aria-label="Zapri spremembo gesla">×</button><form method="post" action="/spremeni-geslo"><p class="eyebrow">Varnost računa</p><h2>{{'Nastavi geslo' if auth_method == 'google' else 'Spremeni geslo'}}</h2>
% if auth_method != 'google':
<label>Trenutno geslo<input type="password" name="current_password" required autocomplete="current-password"></label>
% else:
<p>Ker si prijavljen z varno preverjenim Google računom, lahko po želji nastaviš tudi geslo za rezervno prijavo.</p>
% end
<label>Novo geslo<input type="password" name="new_password" minlength="8" required autocomplete="new-password"></label><label>Ponovi novo geslo<input type="password" name="confirmation" minlength="8" required autocomplete="new-password"></label><div class="dialog-actions"><button type="button" class="button secondary change-password-cancel">Prekliči</button><button type="submit" class="button primary">Shrani geslo</button></div></form></dialog>
<script src="/static/app.js?v=8"></script><script src="/static/push.js?v=1" defer></script></body></html>
