<!doctype html>
<html lang="sl" data-theme="light" data-permissions="{{','.join(sorted(permissions))}}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{title}} · Upravljanje zbora</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/static/styles.css?v=7"></head>
<body>
<aside class="sidebar"><a class="brand" href="/"><span class="brand-mark">𝄞</span><span>Upravljanje zbora<small>Administracija in program</small></span></a><nav aria-label="Glavna navigacija"><a class="{{'active' if active == 'dashboard' else ''}}" href="/"><span>⌂</span>Nadzorna plošča</a><a class="{{'active' if active in ('members','member_detail','roles') else ''}}" href="/clani"><span>♟</span>Člani zbora</a><a class="{{'active' if active in ('songs','song_detail') else ''}}" href="/program"><span>♫</span>Program zbora</a><a class="{{'active' if active in ('events','event_detail') else ''}}" href="/dogodki"><span>▷</span>Vaje in dogodki</a><a class="{{'active' if active == 'attendance' else ''}}" href="/prisotnost"><span>✓</span>Prisotnost</a><a class="{{'active' if active == 'treasury' else ''}}" href="/blagajna"><span>€</span>Blagajna zbora</a></nav><div class="sidebar-footer"><div class="avatar">{{current_user['first_name'][0]}}{{current_user['last_name'][0]}}</div><div><strong>{{current_user['first_name']}} {{current_user['last_name']}}</strong><small>{{', '.join(current_user['roles'])}}</small></div><button class="icon-button" data-account-modal aria-label="Odpri uporabniški meni">•••</button></div></aside>
<main class="main"><header class="topbar"><button class="mobile-menu" aria-label="Odpri meni">☰</button><div><p class="eyebrow">Upravljanje zbora</p><h1>{{title}}</h1></div><div class="top-actions"><a class="home-shortcut" href="/">⌂ Domov</a><button class="icon-button theme-toggle" data-theme-toggle aria-label="Preklopi temni način">◐</button><button class="avatar avatar-button" data-account-modal aria-label="Uporabniški račun {{current_user['first_name']}} {{current_user['last_name']}}">{{current_user['first_name'][0]}}{{current_user['last_name'][0]}}</button></div></header><section class="content">
% include(view, **locals())
</section></main>
<div id="toast" role="status" aria-live="polite" data-message="{{message}}"></div>
<dialog id="account-dialog" class="account-dialog"><button class="account-close dialog-close" aria-label="Zapri uporabniški račun">×</button><div class="account-profile"><span class="avatar xlarge">{{current_user['first_name'][0]}}{{current_user['last_name'][0]}}</span><div><p class="eyebrow">Prijavljeni uporabnik</p><h2>{{current_user['first_name']}} {{current_user['last_name']}}</h2><p>{{current_user['email']}}</p></div></div><p class="permission-note"><strong>Vloge:</strong> {{', '.join(current_user['roles'])}}</p><div class="dialog-actions"><button class="button secondary" data-change-password>Spremeni geslo</button><a class="button danger" href="/odjava">Odjava</a></div></dialog>
<dialog id="change-password-dialog"><button class="change-password-close dialog-close" aria-label="Zapri spremembo gesla">×</button><form method="post" action="/spremeni-geslo"><p class="eyebrow">Varnost računa</p><h2>Spremeni geslo</h2><label>Trenutno geslo<input type="password" name="current_password" required autocomplete="current-password"></label><label>Novo geslo<input type="password" name="new_password" minlength="8" required autocomplete="new-password"></label><label>Ponovi novo geslo<input type="password" name="confirmation" minlength="8" required autocomplete="new-password"></label><div class="dialog-actions"><button type="button" class="button secondary change-password-cancel">Prekliči</button><button type="submit" class="button primary">Shrani geslo</button></div></form></dialog>
<dialog id="reset-password-dialog"><button class="reset-password-close dialog-close" aria-label="Zapri ponastavitev gesla">×</button><form id="reset-password-form" method="post"><p class="eyebrow">Varnost računa</p><h2>Ponastavi geslo</h2><p>Začasno geslo bo enako uporabniškemu imenu <strong id="reset-username"></strong>. Član ga bo moral ob naslednji prijavi spremeniti.</p><div class="dialog-actions"><button type="button" class="button secondary reset-password-cancel">Prekliči</button><button type="submit" class="button primary">Ponastavi geslo</button></div></form></dialog>
<script src="/static/app.js?v=6"></script></body></html>
