<div class="page-tools"><span class="spacer"></span><button class="button primary" data-transaction-dialog data-create-dialog data-permission="treasury">＋ Dodaj transakcijo</button></div>
<div class="treasury-kpis"><article class="card"><p>Trenutno stanje</p><strong>{{'{:,.2f}'.format(data['balance']).replace(',', ' ')}} €</strong></article><article class="card income"><p>Prihodki</p><strong>+ {{'{:,.2f}'.format(data['income']).replace(',', ' ')}} €</strong></article><article class="card expense"><p>Odhodki</p><strong>− {{'{:,.2f}'.format(data['expenses']).replace(',', ' ')}} €</strong></article><article class="card unsettled"><p>Še ni poravnano</p><strong>{{'{:,.2f}'.format(data['unsettled']).replace(',', ' ')}} €</strong></article></div>
<article class="card table-card"><div class="table-meta"><p><strong>Prihodki in odhodki</strong><span>Pregled finančnega poslovanja zbora</span></p></div><div class="table-wrap"><table class="treasury-table"><thead><tr><th>Datum</th><th>Opis</th><th>Kdo je založil / dal denar</th><th>Vrsta</th><th>Znesek</th><th>Poravnano</th><th></th></tr></thead><tbody>
% for item in data['transactions']:
<tr><td>{{item['date']}}</td><td><strong>{{item['description']}}</strong></td><td><span class="person"><span class="avatar small">{{''.join(word[0] for word in item['person'].split()[:2])}}</span>{{item['person']}}</span></td><td><span class="transaction-kind {{'income' if item['kind'] == 'Prihodek' else 'expense'}}">{{item['kind']}}</span></td><td><strong class="amount {{'income' if item['kind'] == 'Prihodek' else 'expense'}}">{{'+' if item['kind'] == 'Prihodek' else '−'}} {{'{:,.2f}'.format(item['amount']).replace(',', ' ')}} €</strong></td><td><form method="post" action="/blagajna/{{item['id']}}/poravnano" class="settled-form"><label class="status-check" title="Označi, ali je transakcija poravnana"><input type="checkbox" name="settled" value="1" {{'checked' if item['settled'] else ''}} data-auto-submit><span>{{'Poravnano' if item['settled'] else 'Odprto'}}</span></label></form></td><td><button class="icon-button" data-transaction-edit="{{item['id']}}" data-permission="treasury" aria-label="Uredi transakcijo {{item['description']}}">✎</button></td></tr>
<dialog id="transaction-edit-{{item['id']}}"><button class="dialog-close transaction-edit-close" aria-label="Zapri">×</button><form method="post" action="/blagajna/{{item['id']}}/uredi"><p class="eyebrow">Blagajna</p><h2>Uredi transakcijo</h2><div class="form-grid"><label>Datum<input type="date" name="date" value="{{item['raw_date'].isoformat()}}" required></label><label>Vrsta<select name="kind"><option {{'selected' if item['kind'] == 'Prihodek' else ''}}>Prihodek</option><option {{'selected' if item['kind'] == 'Odhodek' else ''}}>Odhodek</option></select></label><label>Opis<input name="description" value="{{item['description']}}" required></label><label>Kdo je dal ali založil denar<input name="person_name" value="{{item['person']}}" required></label><label>Znesek<input type="number" name="amount" min="0.01" step="0.01" value="{{item['amount']}}" required></label></div><label class="check standalone-check"><input type="checkbox" name="settled" value="1" {{'checked' if item['settled'] else ''}}><span>Poravnano</span></label><div class="dialog-actions"><button type="button" class="button secondary transaction-edit-cancel">Prekliči</button><button type="submit" class="button primary">Shrani spremembe</button></div></form></dialog>
% end
% if not data['transactions']:
<tr><td colspan="7"><div class="empty-state"><span>€</span><h3>Ni še nobene transakcije</h3><p>Dodaj prvi prihodek ali odhodek zborovske blagajne.</p><button class="button primary" data-transaction-dialog data-permission="treasury">Dodaj transakcijo</button></div></td></tr>
% end
</tbody></table></div></article>
<dialog id="transaction-dialog"><button class="transaction-dialog-close dialog-close" aria-label="Zapri">×</button><form method="post" action="/blagajna"><p class="eyebrow">Blagajna</p><h2>Dodaj transakcijo</h2><div class="form-grid"><label>Datum<input type="date" name="date" required></label><label>Vrsta<select name="kind"><option>Prihodek</option><option>Odhodek</option></select></label><label>Opis<input name="description" required></label><label>Kdo je dal ali založil denar<input name="person_name" required></label><label>Znesek<input type="number" name="amount" min="0.01" step="0.01" required></label></div><label class="check standalone-check"><input type="checkbox" name="settled" value="1"><span>Poravnano</span></label><div class="dialog-actions"><button type="button" class="button secondary transaction-dialog-cancel">Prekliči</button><button type="submit" class="button primary">Shrani transakcijo</button></div></form></dialog>
